version: '3'
services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MYSQL_DATABASE: $MYSQL_DATABASE
        MYSQL_USER: $MYSQL_USER
        MYSQL_PASSWORD: $MYSQL_PASSWORD
    ports:
      - $OBBLM_PORT:80
    links:
      - 'mariadb'

  mariadb:
    image: mariadb:10.1
    volumes:
      - mariadb:/var/lib/mysql
    env_file: .env

volumes:
  mariadb: